name: getx_cleanarch
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: ^2.2.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  http: ^0.13.4
  get: ^4.6.5
  google_fonts: ^3.0.1
  shimmer: ^2.0.0
  intl: ^0.17.0
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
